/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface DefaultInputValidationInterface extends ethers.utils.Interface {
  functions: {
    "validateInput(uint256,uint256,uint256,uint256,bool)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "validateInput",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "validateInput",
    data: BytesLike
  ): Result;

  events: {};
}

export class DefaultInputValidation extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: DefaultInputValidationInterface;

  functions: {
    validateInput(
      period: BigNumberish,
      arg1: BigNumberish,
      strike: BigNumberish,
      currentPrice: BigNumberish,
      arg4: boolean,
      overrides?: CallOverrides
    ): Promise<{
      0: void;
    }>;

    "validateInput(uint256,uint256,uint256,uint256,bool)"(
      period: BigNumberish,
      arg1: BigNumberish,
      strike: BigNumberish,
      currentPrice: BigNumberish,
      arg4: boolean,
      overrides?: CallOverrides
    ): Promise<{
      0: void;
    }>;
  };

  validateInput(
    period: BigNumberish,
    arg1: BigNumberish,
    strike: BigNumberish,
    currentPrice: BigNumberish,
    arg4: boolean,
    overrides?: CallOverrides
  ): Promise<void>;

  "validateInput(uint256,uint256,uint256,uint256,bool)"(
    period: BigNumberish,
    arg1: BigNumberish,
    strike: BigNumberish,
    currentPrice: BigNumberish,
    arg4: boolean,
    overrides?: CallOverrides
  ): Promise<void>;

  callStatic: {
    validateInput(
      period: BigNumberish,
      arg1: BigNumberish,
      strike: BigNumberish,
      currentPrice: BigNumberish,
      arg4: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "validateInput(uint256,uint256,uint256,uint256,bool)"(
      period: BigNumberish,
      arg1: BigNumberish,
      strike: BigNumberish,
      currentPrice: BigNumberish,
      arg4: boolean,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    validateInput(
      period: BigNumberish,
      arg1: BigNumberish,
      strike: BigNumberish,
      currentPrice: BigNumberish,
      arg4: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "validateInput(uint256,uint256,uint256,uint256,bool)"(
      period: BigNumberish,
      arg1: BigNumberish,
      strike: BigNumberish,
      currentPrice: BigNumberish,
      arg4: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    validateInput(
      period: BigNumberish,
      arg1: BigNumberish,
      strike: BigNumberish,
      currentPrice: BigNumberish,
      arg4: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "validateInput(uint256,uint256,uint256,uint256,bool)"(
      period: BigNumberish,
      arg1: BigNumberish,
      strike: BigNumberish,
      currentPrice: BigNumberish,
      arg4: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
