/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { InitialInputConstraint } from "./InitialInputConstraint";

export class InitialInputConstraintFactory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<InitialInputConstraint> {
    return super.deploy(overrides || {}) as Promise<InitialInputConstraint>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): InitialInputConstraint {
    return super.attach(address) as InitialInputConstraint;
  }
  connect(signer: Signer): InitialInputConstraintFactory {
    return super.connect(signer) as InitialInputConstraintFactory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): InitialInputConstraint {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as InitialInputConstraint;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "period",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "strike",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "currentPrice",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    name: "validateInput",
    outputs: [],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610149806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063819a572614610030575b600080fd5b61004361003e3660046100c3565b610045565b005b8282146100bc578462278d00146100bc5760405162461bcd60e51b815260206004820152603160248201527f4f6e6c7920333020646179732065787069727920737570706f7274656420666f60448201527072206e6f6e2041544d206f7074696f6e7360781b606482015260840160405180910390fd5b5050505050565b600080600080600060a086880312156100da578081fd5b8535945060208601359350604086013592506060860135915060808601358015158114610105578182fd5b80915050929550929590935056fea2646970667358221220fd070b29abf3e3265106ba05cf3f9bf8cb1d27ac5a48a4483f9bfbd6d9edbaf364736f6c63430008040033";
