/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IPoolInputValidator } from "./IPoolInputValidator";

export class IPoolInputValidatorFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPoolInputValidator {
    return new Contract(address, _abi, signerOrProvider) as IPoolInputValidator;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "period",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "strike",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "isCall",
        type: "bool",
      },
    ],
    name: "validateInput",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
