/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IPriceCalculatorInterface extends ethers.utils.Interface {
  functions: {
    "calculateTotalPremium(uint256,uint256,uint256,bool,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "calculateTotalPremium",
    values: [BigNumberish, BigNumberish, BigNumberish, boolean, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "calculateTotalPremium",
    data: BytesLike
  ): Result;

  events: {};
}

export class IPriceCalculator extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IPriceCalculatorInterface;

  functions: {
    calculateTotalPremium(
      period: BigNumberish,
      amount: BigNumberish,
      strike: BigNumberish,
      isCall: boolean,
      outDecimals: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      settlementFee: BigNumber;
      premium: BigNumber;
      0: BigNumber;
      1: BigNumber;
    }>;

    "calculateTotalPremium(uint256,uint256,uint256,bool,uint256)"(
      period: BigNumberish,
      amount: BigNumberish,
      strike: BigNumberish,
      isCall: boolean,
      outDecimals: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      settlementFee: BigNumber;
      premium: BigNumber;
      0: BigNumber;
      1: BigNumber;
    }>;
  };

  calculateTotalPremium(
    period: BigNumberish,
    amount: BigNumberish,
    strike: BigNumberish,
    isCall: boolean,
    outDecimals: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    settlementFee: BigNumber;
    premium: BigNumber;
    0: BigNumber;
    1: BigNumber;
  }>;

  "calculateTotalPremium(uint256,uint256,uint256,bool,uint256)"(
    period: BigNumberish,
    amount: BigNumberish,
    strike: BigNumberish,
    isCall: boolean,
    outDecimals: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    settlementFee: BigNumber;
    premium: BigNumber;
    0: BigNumber;
    1: BigNumber;
  }>;

  callStatic: {
    calculateTotalPremium(
      period: BigNumberish,
      amount: BigNumberish,
      strike: BigNumberish,
      isCall: boolean,
      outDecimals: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      settlementFee: BigNumber;
      premium: BigNumber;
      0: BigNumber;
      1: BigNumber;
    }>;

    "calculateTotalPremium(uint256,uint256,uint256,bool,uint256)"(
      period: BigNumberish,
      amount: BigNumberish,
      strike: BigNumberish,
      isCall: boolean,
      outDecimals: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      settlementFee: BigNumber;
      premium: BigNumber;
      0: BigNumber;
      1: BigNumber;
    }>;
  };

  filters: {};

  estimateGas: {
    calculateTotalPremium(
      period: BigNumberish,
      amount: BigNumberish,
      strike: BigNumberish,
      isCall: boolean,
      outDecimals: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "calculateTotalPremium(uint256,uint256,uint256,bool,uint256)"(
      period: BigNumberish,
      amount: BigNumberish,
      strike: BigNumberish,
      isCall: boolean,
      outDecimals: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    calculateTotalPremium(
      period: BigNumberish,
      amount: BigNumberish,
      strike: BigNumberish,
      isCall: boolean,
      outDecimals: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "calculateTotalPremium(uint256,uint256,uint256,bool,uint256)"(
      period: BigNumberish,
      amount: BigNumberish,
      strike: BigNumberish,
      isCall: boolean,
      outDecimals: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
