/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IRewardsManager } from "./IRewardsManager";

export class IRewardsManagerFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRewardsManager {
    return new Contract(address, _abi, signerOrProvider) as IRewardsManager;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "buyer",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "notionalSize",
        type: "uint256",
      },
    ],
    name: "callBought",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "provider",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "notionalSize",
        type: "uint256",
      },
    ],
    name: "liquidityProvided",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "buyer",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "notionalSize",
        type: "uint256",
      },
    ],
    name: "putBought",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
