/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IRewardsManagerInterface extends ethers.utils.Interface {
  functions: {
    "callBought(address,uint256)": FunctionFragment;
    "liquidityProvided(address,uint256)": FunctionFragment;
    "putBought(address,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "callBought",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidityProvided",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "putBought",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "callBought", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "liquidityProvided",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "putBought", data: BytesLike): Result;

  events: {};
}

export class IRewardsManager extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IRewardsManagerInterface;

  functions: {
    callBought(
      buyer: string,
      notionalSize: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "callBought(address,uint256)"(
      buyer: string,
      notionalSize: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    liquidityProvided(
      provider: string,
      notionalSize: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "liquidityProvided(address,uint256)"(
      provider: string,
      notionalSize: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    putBought(
      buyer: string,
      notionalSize: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "putBought(address,uint256)"(
      buyer: string,
      notionalSize: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  callBought(
    buyer: string,
    notionalSize: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "callBought(address,uint256)"(
    buyer: string,
    notionalSize: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  liquidityProvided(
    provider: string,
    notionalSize: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "liquidityProvided(address,uint256)"(
    provider: string,
    notionalSize: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  putBought(
    buyer: string,
    notionalSize: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "putBought(address,uint256)"(
    buyer: string,
    notionalSize: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    callBought(
      buyer: string,
      notionalSize: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "callBought(address,uint256)"(
      buyer: string,
      notionalSize: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    liquidityProvided(
      provider: string,
      notionalSize: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "liquidityProvided(address,uint256)"(
      provider: string,
      notionalSize: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    putBought(
      buyer: string,
      notionalSize: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "putBought(address,uint256)"(
      buyer: string,
      notionalSize: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    callBought(
      buyer: string,
      notionalSize: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "callBought(address,uint256)"(
      buyer: string,
      notionalSize: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    liquidityProvided(
      provider: string,
      notionalSize: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "liquidityProvided(address,uint256)"(
      provider: string,
      notionalSize: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    putBought(
      buyer: string,
      notionalSize: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "putBought(address,uint256)"(
      buyer: string,
      notionalSize: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    callBought(
      buyer: string,
      notionalSize: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "callBought(address,uint256)"(
      buyer: string,
      notionalSize: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    liquidityProvided(
      provider: string,
      notionalSize: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "liquidityProvided(address,uint256)"(
      provider: string,
      notionalSize: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    putBought(
      buyer: string,
      notionalSize: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "putBought(address,uint256)"(
      buyer: string,
      notionalSize: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
